-- MySQL Script generated by MySQL Workbench
-- Wed Dec  5 02:49:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema news_clustering_batch
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema news_clustering_batch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `news_clustering_batch` DEFAULT CHARACTER SET utf8 ;
USE `news_clustering_batch` ;

-- -----------------------------------------------------
-- Table `news_clustering_batch`.`brackets_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_clustering_batch`.`brackets_news` (
  `office_id` VARCHAR(3) NOT NULL,
  `article_id` VARCHAR(10) NOT NULL,
  `section` VARCHAR(50) NOT NULL,
  `dt` DATETIME NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `reporter` VARCHAR(100) NOT NULL,
  `title_keyword` VARCHAR(100) NOT NULL,
  `content_keyword` VARCHAR(200) NULL,
  PRIMARY KEY (`office_id`, `article_id`),
  INDEX `idx_office_id_article_id` (`office_id` ASC, `article_id` ASC),
  INDEX `idx_dt` (`dt` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_clustering_batch`.`non_brackets_news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_clustering_batch`.`non_brackets_news` (
  `office_id` VARCHAR(3) NOT NULL,
  `article_id` VARCHAR(10) NOT NULL,
  `section` VARCHAR(50) NOT NULL,
  `dt` DATETIME NOT NULL,
  `title` VARCHAR(200) NOT NULL,
  `content` TEXT NOT NULL,
  `reporter` VARCHAR(100) NOT NULL,
  `title_keyword` VARCHAR(100) NOT NULL,
  `content_keyword` VARCHAR(200) NULL,
  PRIMARY KEY (`office_id`, `article_id`),
  INDEX `idx_office_id_article_id` (`office_id` ASC, `article_id` ASC),
  INDEX `idx_dt` (`dt` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_clustering_batch`.`series`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_clustering_batch`.`series` (
  `series_id` BIGINT NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `keyword` VARCHAR(100) NOT NULL,
  `cnt` INT NOT NULL,
  `create_dt` DATETIME NOT NULL,
  `update_dt` DATETIME NOT NULL,
  PRIMARY KEY (`series_id`),
  INDEX `idx_create_dt` (`create_dt` ASC),
  INDEX `idx_update_dt` (`update_dt` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `news_clustering_batch`.`series_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `news_clustering_batch`.`series_item` (
  `id` BIGINT NOT NULL,
  `series_id` BIGINT NOT NULL,
  `office_id` VARCHAR(3) NOT NULL,
  `article_id` VARCHAR(10) NOT NULL,
  `id_completed` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_series_id` (`series_id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
